steps:
  # Run tests
  - name: golang:1.19
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go test -v ./...

  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/eoplatform:$SHORT_SHA', '.']

  # Docker push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/eoplatform:$SHORT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'eoplatform',
        '--image=gcr.io/$PROJECT_ID/eoplatform:$SHORT_SHA',
        '--region=asia-southeast2',
        '--platform=managed',
        '--allow-unauthenticated',
      ]

# Store image
images:
  - gcr.io/$PROJECT_ID/eoplatform:$SHORT_SHA
